id: 7fbd2396d08d4b4d8759525dfabca927
initial_creation_type: ocr
source_metadata:
  volumes:
    8046db8157be43aba210fc59c681cdfd:
      base_file: v077.txt
      image_group_id: I1PD95923
      title: བསམ་གཏན་གྱི་སྒྲོན་མ་ཞེས་བྱ་བའི་མན་ངག།
      total_pages: 1254
      volume_number: 78
